//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodrozeSluzbowe
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessTrips
    {
        public int Id { get; set; }
        public int CarId { get; set; }
        public int DestinationId { get; set; }
        public int UserId { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public bool Active { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Destinations Destinations { get; set; }
        public virtual Users Users { get; set; }
    }
}
