//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodrozeSluzbowe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        public Departments()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int Id { get; set; }
        public string DepartmentName { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
    }
}
