//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodrozeSluzbowe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destinations
    {
        public Destinations()
        {
            this.BusinessTrips = new HashSet<BusinessTrips>();
        }
    
        public int Id { get; set; }
        public string Address { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<BusinessTrips> BusinessTrips { get; set; }
    }
}
