//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PodrozeSluzbowe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PodrozeEntities : DbContext
    {
        public PodrozeEntities()
            : base("name=PodrozeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusinessTrips> BusinessTrips { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Destinations> Destinations { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
